version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - '3000:3000'
    volumes:
      - C:\Users\Yanislav\Documents\docker_volumes\grafana-storage:/var/lib/grafana
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: twitch_insights
      MYSQL_USER: yanislav
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - C:\Users\Yanislav\Documents\docker_volumes\mysql-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitch-queue-events
    restart: unless-stopped
    command: python -m ingest.queue_events
    volumes:
      - C:\Users\Yanislav\.aws:/root/.aws
volumes:
  grafana-storage: {}
  mysql-data: {}
